import 'package:flutter/material.dart';

class AppLocalization {
  final Locale locale;

  AppLocalization(this.locale);

  static final Map<String, Map<String, String>> _translations = {
    'en': {
      'app_name': 'BUT Wallet',
      'balance': 'Total Balance',
      'send': 'Send',
      'receive': 'Receive',
      'swap': 'Swap',
      'stake': 'Stake',
      'nft': 'NFT',
      'settings': 'Settings',
      'language': 'Language',
      'security': 'Security Keys',
      'recovery': 'Recovery',
      'create_wallet': 'Create New Wallet',
      'import_wallet': 'Import Existing Wallet',
      'save_phrase': 'SAVE YOUR RECOVERY PHRASE',
      'send_but': 'Send BUT',
      'receive_but': 'Receive BUT',
      'swap_tokens': 'Swap Tokens',
      'staking': 'Staking',
      'nft_gallery': 'NFT Gallery',
      'system_restore': 'System Restore',
      'address_mapper': 'Address Mapper',
      'amount': 'Amount',
      'recipient': 'Recipient Address',
      'fee': 'Network Fee',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'success': 'Success',
      'error': 'Error',
      'loading': 'Loading...',
      'no_data': 'No data yet',
      'search': 'Search',
      'copy': 'Copy',
      'share': 'Share',
      'delete': 'Delete',
      'edit': 'Edit',
      'save': 'Save',
      'close': 'Close',
      'next': 'Next',
      'back': 'Back',
      'done': 'Done',
      'yes': 'Yes',
      'no': 'No',
      'warning': 'Warning',
      'info': 'Information',
      'version': 'Version',
      'about': 'About',
      'logout': 'Logout',
      'biometric': 'Biometric Login',
      'pin': 'Enter PIN',
      'setup_pin': 'Setup New PIN',
      'mnemonic': 'Recovery Phrase',
      'but_network': 'BUT Network',
      'but_price': 'BUT Price',
      'market_cap': 'Market Cap',
      'volume': '24h Volume',
      'transactions': 'Transactions',
      'history': 'History',
      'from': 'From',
      'to': 'To',
      'date': 'Date',
      'status': 'Status',
      'completed': 'Completed',
      'pending': 'Pending',
      'failed': 'Failed',
    },
    'hi': {
      'app_name': 'BUT वॉलेट',
      'balance': 'कुल बैलेंस',
      'send': 'भेजें',
      'receive': 'प्राप्त करें',
      'swap': 'स्वैप',
      'stake': 'स्टेक',
      'nft': 'एनएफटी',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'security': 'सुरक्षा कीज़',
      'recovery': 'रिकवरी',
      'create_wallet': 'नया वॉलेट बनाएँ',
      'import_wallet': 'वॉलेट इम्पोर्ट करें',
      'save_phrase': 'अपना रिकवरी फ्रेज़ सेव करें',
      'send_but': 'BUT भेजें',
      'receive_but': 'BUT प्राप्त करें',
      'swap_tokens': 'टोकन स्वैप करें',
      'staking': 'स्टेकिंग',
      'nft_gallery': 'NFT गैलरी',
      'system_restore': 'सिस्टम रिस्टोर',
      'address_mapper': 'एड्रेस मैपर',
      'amount': 'राशि',
      'recipient': 'प्राप्तकर्ता का पता',
      'fee': 'नेटवर्क फ़ीस',
      'confirm': 'पुष्टि करें',
      'cancel': 'रद्द करें',
      'success': 'सफल',
      'error': 'त्रुटि',
      'loading': 'लोड हो रहा है...',
      'no_data': 'अभी कोई डेटा नहीं',
      'search': 'खोजें',
      'copy': 'कॉपी करें',
      'share': 'शेयर करें',
      'delete': 'हटाएँ',
      'edit': 'संपादित करें',
      'save': 'सेव करें',
      'close': 'बंद करें',
      'next': 'अगला',
      'back': 'पीछे',
      'done': 'पूर्ण',
      'yes': 'हाँ',
      'no': 'नहीं',
      'warning': 'चेतावनी',
      'info': 'जानकारी',
      'version': 'संस्करण',
      'about': 'के बारे में',
      'logout': 'लॉग आउट',
      'biometric': 'बायोमेट्रिक लॉगिन',
      'pin': 'पिन दर्ज करें',
      'setup_pin': 'नया पिन सेट करें',
      'mnemonic': 'रिकवरी फ्रेज़',
      'but_network': 'BUT नेटवर्क',
      'but_price': 'BUT की कीमत',
      'market_cap': 'मार्केट कैप',
      'volume': '24 घंटे का वॉल्यूम',
      'transactions': 'लेन-देन',
      'history': 'इतिहास',
      'from': 'से',
      'to': 'तक',
      'date': 'तारीख',
      'status': 'स्थिति',
      'completed': 'पूर्ण',
      'pending': 'लंबित',
      'failed': 'असफल',
    },
    'es': {
      'app_name': 'BUT Billetera',
      'balance': 'Saldo Total',
      'send': 'Enviar',
      'receive': 'Recibir',
      'swap': 'Intercambiar',
      'stake': 'Apostar',
      'nft': 'NFT',
      'settings': 'Configuración',
      'language': 'Idioma',
      'security': 'Llaves de Seguridad',
      'recovery': 'Recuperación',
      'create_wallet': 'Crear Nueva Billetera',
      'import_wallet': 'Importar Billetera',
      'save_phrase': 'GUARDE SU FRASE DE RECUPERACIÓN',
      'send_but': 'Enviar BUT',
      'receive_but': 'Recibir BUT',
      'swap_tokens': 'Intercambiar Tokens',
      'staking': 'Staking',
      'nft_gallery': 'Galería NFT',
      'system_restore': 'Restaurar Sistema',
      'address_mapper': 'Mapeador de Direcciones',
      'amount': 'Cantidad',
      'recipient': 'Dirección del Destinatario',
      'fee': 'Tarifa de Red',
      'confirm': 'Confirmar',
      'cancel': 'Cancelar',
      'success': 'Éxito',
      'error': 'Error',
      'loading': 'Cargando...',
      'no_data': 'Sin datos aún',
      'search': 'Buscar',
      'copy': 'Copiar',
      'share': 'Compartir',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'save': 'Guardar',
      'close': 'Cerrar',
      'next': 'Siguiente',
      'back': 'Atrás',
      'done': 'Hecho',
      'yes': 'Sí',
      'no': 'No',
      'warning': 'Advertencia',
      'info': 'Información',
      'version': 'Versión',
      'about': 'Acerca de',
      'logout': 'Cerrar Sesión',
      'biometric': 'Inicio Biométrico',
      'pin': 'Ingresar PIN',
      'setup_pin': 'Configurar Nuevo PIN',
      'mnemonic': 'Frase de Recuperación',
      'but_network': 'BUT Network',
      'completed': 'Completado',
      'pending': 'Pendiente',
      'failed': 'Fallido',
    },
    'ar': {
      'app_name': 'محفظة BUT',
      'balance': 'الرصيد الإجمالي',
      'send': 'إرسال',
      'receive': 'استلام',
      'swap': 'مبادلة',
      'stake': 'تخزين',
      'nft': 'NFT',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'security': 'مفاتيح الأمان',
      'recovery': 'استعادة',
      'create_wallet': 'إنشاء محفظة جديدة',
      'import_wallet': 'استيراد محفظة',
      'save_phrase': 'احفظ عبارة الاستعادة',
      'send_but': 'إرسال BUT',
      'receive_but': 'استلام BUT',
      'amount': 'المبلغ',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'success': 'نجاح',
      'error': 'خطأ',
      'loading': 'جار التحميل...',
      'copy': 'نسخ',
      'save': 'حفظ',
      'close': 'إغلاق',
      'yes': 'نعم',
      'no': 'لا',
      'completed': 'مكتمل',
      'pending': 'قيد الانتظار',
      'failed': 'فشل',
    },
  };

  String translate(String key) {
    if (_translations.containsKey(locale.languageCode)) {
      return _translations[locale.languageCode]?[key] ?? _translations['en']?[key] ?? key;
    }
    return _translations['en']?[key] ?? key;
  }

  static String of(BuildContext context, String key) {
    final localization = Localizations.of<AppLocalization>(context, AppLocalization);
    return localization?.translate(key) ?? key;
  }

  static List<Map<String, String>> getSupportedLanguages() {
    return [
      {'code': 'en', 'name': 'English', 'native': 'English'},
      {'code': 'hi', 'name': 'Hindi', 'native': 'हिन्दी'},
      {'code': 'es', 'name': 'Spanish', 'native': 'Español'},
      {'code': 'ar', 'name': 'Arabic', 'native': 'العربية'},
    ];
  }
}

class AppLocalizationDelegate extends LocalizationsDelegate<AppLocalization> {
  const AppLocalizationDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'hi', 'es', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalization> load(Locale locale) async {
    return AppLocalization(locale);
  }

  @override
  bool shouldReload(AppLocalizationDelegate old) => false;
}
